"""empty message

Revision ID: 5061b2035f44
Revises: 4c14f949589
Create Date: 2014-07-05 19:04:02.905232

"""

# revision identifiers, used by Alembic.
revision = '5061b2035f44'
down_revision = '4c14f949589'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_code'), 'events', ['code'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_code'), table_name='events')
    op.drop_table('events')
    ### end Alembic commands ###
