"""empty message

Revision ID: 5b240810633
Revises: 5061b2035f44
Create Date: 2014-07-05 20:12:01.388287

"""

# revision identifiers, used by Alembic.
revision = '5b240810633'
down_revision = '5061b2035f44'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkins',
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['events.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('checkins')
    ### end Alembic commands ###
